# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: "registry.k8s.io/e2e-test-images/agnhost"
  tag: "2.39"
  arch: "amd64"
secret:
  name: "echo"
  env: "TELE_TOKEN"
  key: "token"
  value: "<your-base64-encoded-secret>"