#!/bin/bash

# Check if the correct number of arguments is provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <namespace> <resource-type>"
    exit 1
fi

NAMESPACE=$1
RESOURCE_TYPE=$2

# Retrieve resource usage statistics from Kubernetes
kubectl top $RESOURCE_TYPE -n $NAMESPACE --no-headers | awk -v resource_type=$RESOURCE_TYPE -v namespace=$NAMESPACE '{
    # Print formatted output
    print "Resource: "resource_type", Namespace: "namespace", Name: "$1", CPU: "$2", Memory: "$3
}'
